name = "kendrick"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "kendrick-db"
database_id = "dcba75e2-c77a-4218-bd62-fff9b9ebe707"

[vars]
OWNER_EMAIL = "veridiana@kendrick.com"
APP_NAME = "Kendrick Consultoria Digital"

# Agrega en el dashboard de Cloudflare → Pages → Settings → Variables:
# RESEND_API_KEY = "re_xxxx"





